project:
  type: book
  resources: "correctional_stats_environment1b.RData"
book:
  title: "Statistical Report on OTIS"
  author:
    - name: "Vansh Singh Ruhela"
      orcid: "0009-0004-1750-3592"
      affiliations:
        - name: "Centre for Criminology & Sociolegal Studies, School of Graduate Studies, University of Toronto St. George"
          city: "Toronto"
          state: "ON"
          country: "Canada" 
  search: true 
  repo-url: https://github.com/ruhelavansh-oss/OTIS-Report
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  date: "2026-01-01"
  sidebar:
    title: "OTIS Report"
    logo: cvr1b.png
    logo-alt: "Book cover"
    style: docked
    background: light
  chapters:
    - index.qmd
    - intro.qmd
    - descriptives.qmd
    - results.qmd
    - notez1a.qmd
    - references.qmd
bibliography: references.bib
format:
  html:
    theme:
      light:
        - cosmo
        - brand
      dark:
        - darkly
        - dracula
    highlight-style: github
    comments:
      hypothesis: false
    other-links:
      - text: Partial Notebook
        href: "https://vanshsinghruhela-statistical-report-on-restrictive-confinement.share.connect.posit.cloud"
      - text: Prelim. DPR
        href: "https://vanshsinghruhela-statistical-report-on-restrictive-confinement.share.connect.posit.cloud/prelim_report.html"
      - text: Row Exp. DPR
        href: "https://vanshsinghruhela-statistical-report-on-restrictive-confinement.share.connect.posit.cloud/final_report.html"

    include-in-header:
      - includez/rename-other-links.html
      - includez/sidebar-title-home.html
    code-fold: true
    toc: true
    number-sections: true
  docx:
    toc: true
    highlight-style: github
  pdf:
    documentclass: scrreprt
    toc: true
    keep-tex: true
epub:
  cover-image: cvr1b.png
  toc: true
execute:
  warning: false
  message: false
  freeze: true
  cache: true
  eval: true
  echo: true

